# file --mime-type -b sudolightburn.sh
# to see mimetype based on file contents

# xdg-mime query filetype Bicycle.validator.mapcss
# to see mimetype based on declared file extensions

# see https://askubuntu.com/questions/844864/why-the-difference-between-the-results-with-file-mime-type-and-xdg-mime-que
# for description of differences

# in cases where this failed (text/plain gets returned):
# cat ~/.config/mimeapps.list
# change in GUI
# cat ~/.config/mimeapps.list
# revert change, use that code in xdg-mime default 

# xdg-mime query default text/plain
# to see current

# xdg-mime default codium.desktop text/plain
# to change

# .desktop files should be in /usr/share/applications
# https://askubuntu.com/questions/16580/where-are-file-associations-stored

# cat /usr/share/applications/defaults.list
# to see defaults (system ones?)
# can be located with following command:
# locate defaults.list

# cat ~/.config/mimeapps.list
# to user specific stuff, at least in Lubuntu 20.04


# how to do this? For things that report text/plain
# https://askubuntu.com/questions/1328442/programatically-modify-file-associations-using-standard-interface-cases-where-m

---
# is this task actually needed?
# var definition:
# xdg_mime_config_dir: "{{ lookup('env','HOME') }}/.config"
#
#- name: ensure users xdg mime directory exists
#  file:
#    state: directory
#    path: "{{ xdg_mime_config_dir }}"
#    mode: 0700
- name: Install packages with xdg-mime and other helper tools
  apt:
   name:
     - xdg-utils
     - mlocate
   force_apt_get: yes

- name: Set plain text files to be opened with Codium
  become_user: "{{ username_of_a_local_user }}"
  command: "xdg-mime default codium.desktop text/plain"
  changed_when: False

- name: Set files with shell scripts to be opened with Codium
  become_user: "{{ username_of_a_local_user }}"
  command: "xdg-mime default codium.desktop application/x-shellscript"
  changed_when: False

- name: Set TypeScript files to be opened with Codium, override some Qt Linguist misclassification
  become_user: "{{ username_of_a_local_user }}"
  command: "xdg-mime default codium.desktop text/vnd.qt.linguist"
  changed_when: False

- name: Set Java files to be opened with Codium
  become_user: "{{ username_of_a_local_user }}"
  command: "xdg-mime default codium.desktop text/x-java"
  changed_when: False

- name: Set XML files to be opened with Codium
  become_user: "{{ username_of_a_local_user }}"
  command: "xdg-mime default codium.desktop application/xml"
  changed_when: False

- name: Set JS files to be opened with Codium
  become_user: "{{ username_of_a_local_user }}"
  command: "xdg-mime default codium.desktop application/javascript"
  changed_when: False

- name: Really set XML files to be opened with Codium
  become_user: "{{ username_of_a_local_user }}"
  command: "xdg-mime default codium.desktop text/xml"
  changed_when: False

- name: Set .mapcss to be opened with Codium, override some misclassification opening it in Yudit, whatever purpose of that text editor is
  become_user: "{{ username_of_a_local_user }}"
  command: "xdg-mime default codium.desktop text/x-csrc"
  changed_when: False

- name: Set LaTeX files to be opened with Codium
  become_user: "{{ username_of_a_local_user }}"
  command: "xdg-mime default codium.desktop text/x-tex"
  changed_when: False

- name: Set makefile files to be opened with Codium
  become_user: "{{ username_of_a_local_user }}"
  command: "xdg-mime default codium.desktop text/x-makefile"
  changed_when: False

- name: Set pdf files to be opened with Okular
  become_user: "{{ username_of_a_local_user }}"
  command: "xdg-mime default okularApplication_pdf.desktop application/pdf"
  changed_when: False

# ???? is it correct? test
# xdg-mime query default application/epub+zip
- name: Set epubs files to be opened with Okular
  become_user: "{{ username_of_a_local_user }}"
  command: "xdg-mime default okularApplication_epup.desktop application/epub+zip"
  changed_when: False

- name: Set Markdown (md) files to be opened with Ghostwriter
  become_user: "{{ username_of_a_local_user }}"
  command: "xdg-mime default ghostwriter.desktop text/markdown"
  changed_when: False
#- name: Set Markdown (md) files to be opened with ReText
#  become_user: "{{ username_of_a_local_user }}"
#  command: "xdg-mime default me.mitya57.ReText.desktop text/markdown"
#  changed_when: False

