---
- name: bootstrap
  hosts: all
  gather_facts: false
  # if for some reason I need to start supporting CentOS or other OS with yum then
  # https://relativkreativ.at/articles/how-to-install-python-with-ansible
  # has a potential code
  tasks:
    - name: Install python if not installed
      raw: sh -c 'test -x /usr/bin/python3 || (apt-get update && apt-get -y install python3-minimal)'
      register: out
      changed_when: out.stdout != ""
    - set_fact:
        ansible_python_interpreter: /usr/bin/python3
      tags: always
- name: core
  hosts: all
  become: yes
  vars:
    username_of_a_local_user: mateusz
  roles:
    - ansible

- name: basic
  hosts: all
  vars:
    username_of_a_local_user: mateusz
  become: yes
  roles:
    - git
    - ruby # required by legacy install scripts
    - python # required by commitment device scripts
    - dev_tools_basic
    - code_editor_generic_for_everything # listing of tried editors is there
    - stop_upgrade_notifier_popup
    - ripgrep
    - set_default_programs_for_file_types

- name: basic_on_the_main_computer
  hosts: all
  vars:
    username_of_a_local_user: mateusz
  become: yes
  roles:
    - backup_restore_gem
    - backup_gem
    - cron_dependencies # to avoid spurious notifications about failed cron jobs

- name: my_software
  hosts: all
  vars:
    username_of_a_local_user: mateusz
  become: yes
  roles:
    - mnemosyne
    - start_menu_editor
    - program_to_select_monitor_or_monitors_displaying_screen
    - newline_tools
    - android-studio
    #- kotlin # Snap version that is disabled right now (TODO)
    - screencast_screen_capture
    - image_editor_raster
    - inkscape
    - dev_tools_not_critical
    - mail_client
    - paint_equivalent
    - pdf_viewer
    - pdf_editor_add_an_image
    - office_software
    - markdown_viewer
    - epub_reader
    - video_player
    - password_manager # keepass
    - java
    - prepare_system_for_josm
    - youtube_downloader
    - audio_settings_and_debugging
    - checker_what_opens_a_given_file
    - map_carver_dependencies # was borked by npm
                              # The error was: json.decoder.JSONDecodeError
                              # fixed in https://github.com/ansible-collections/community.general/pull/1625
                              # broken in Ansible 2.9.6, fixed in 2.12.10 (see ansible --version)
    - printer_driver_support
    - music_player_with_automatic_ratings
    - print_screen_capture_tool
    - image_viewer_able_to_use_trash
    - set_default_programs_for_file_types
    - borg_backup
    - music_editor
    - install_readable_documentation
    - geojson_viewer
    - ftp_client
    - screen_recorder
    - torrent_client
- name: low_priority_changes
  hosts: all
  vars:
    username_of_a_local_user: mateusz
  become: yes
  roles:
    - spellcheck_dictionaries
    - virtualbox
    - midi_audio_files_player
    - per_project_gem_management
    - archive_unarchive_everything
    - system_dependencies_of_ruby_bindings_for_image_magick
    - system_dependencies_of_scipy_python_package
    - pdf_generator_used_by_recipe_lister
    - flatpak
    - trigger_notifications_popups
    - ugly_workarounds
- name: final_cleanup
  hosts: all
  vars:
    username_of_a_local_user: mateusz
  become: yes
  roles:
    - bloat_removal
    - apt_packages_autoremove_unneded
    - apt_packages_upgrade
    - browser_removal_to_make_selfparental_control_more_efficient
