# https://github.com/retext-project/retext#welcome-to-retext
---
- name: Install ReText
  become: yes # needed iff --user mode is used
  become_user: "{{ username_of_a_local_user }}" # needed iff --user mode is used
  pip:
    name: ReText
    extra_args: --user
- name: Install GhostWriter
  apt:
   name:
     - ghostwriter
   force_apt_get: yes
