# https://github.com/retext-project/retext#welcome-to-retext
---
- name: Install ReText
  become_user: "{{ username_of_a_local_user }}"
  community.general.pipx:
    name: ReText
# https://github.com/KDE/ghostwriter?tab=readme-ov-file#-ghostwriter
- name: Install GhostWriter
  apt:
   name:
     - ghostwriter
   force_apt_get: yes
# https://apps.gnome.org/Apostrophe/
# https://flathub.org/apps/org.gnome.gitlab.somas.Apostrophe
# https://gitlab.gnome.org/World/apostrophe
# available from APT - but in 2025 it was version from 2022
# ysing flatpak would require new dependency in ../meta
- name: Install apostrophe
  community.general.flatpak:
    name: https://dl.flathub.org/repo/appstream/org.gnome.gitlab.somas.Apostrophe.flatpakref
    state: present
