# CURRENT SELECTION:
# visual studio code works OK but...
# codium is the same, without telemetry and similar unwanted stuff

# for quick editing
# geany geany-plugin-addons

# CRITERIA:
# decent text editor that works well out of the box
# - without endless configurations
# - sane defaults
# - but allow configuration
# - must have syntax code higligting
#  - ability to show whitespace (tabs vs spaces) is mandatory
# - preferably showing automated docs info for libraries (in Python, Ruby etc)
# - preferably smart tabs - use tabs/spaces depending on how file is formatted
# - no telemetry
#  - at this point believing that only private and limited data will be used
#    would be silly. This is sad as reasonable telemetry would help everyone.

# REJECTED EDITORS:
# sublime text requires manual configuration to work well
# - https://www.sublimetext.com/docs/3/linux_repositories.html
# gedit is worse than sublime text
# featherpad is unfriendly as a code editor
# - option to distinguish spaces and tabs is deeply buried
#   - Option -> Preferences -> Text -> Show whitespaces
# - and it is using tabs when editing Python files with spaces for intends
# - not showing line numbers by default
# - losing state on OS/program crash
# kate
# - fails on extremely long lines
#   - https://stackoverflow.com/a/70590302/4130619 (but that was Kate 19.12.3 from 2019, in 2022 it was what Ubuntu package included)
# - not showing line numbers by default ( https://superuser.com/q/918189/376651 )


# https://docs.ansible.com/ansible/latest/modules/apt_key_module.html
# https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo

# seems broken - see https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/issues/57
# switch to snap cancer? Measure boot time in case of snap - https://github.com/VSCodium/vscodium#install-with-snap-gnulinux
# switch to VSCode?
---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    state: present
- name: "Add repo"
  apt_repository:
    repo: 'deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main'
- name: "Install codium"
  apt:
    name: codium
    force_apt_get: yes

# note https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/issues/36#note_395793123

# this ansible code replaces following script
# wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | sudo apt-key add -
# echo 'deb https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs/ vscodium main' | sudo tee --append /etc/apt/sources.list
# sudo apt-get -qq update
# sudo apt-get -qq install -y codium > /dev/null # in case of changing this - remember to modify git config

# https://askubuntu.com/questions/616075/how-do-i-install-visual-studio-code/895790#895790
# broken - later 
# starts to complain about duplicated sources
# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EB3E94ADBE1229CF
# sudo add-apt-repository -y "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
# sudo apt-get -qq update
# sudo apt -y install code

# version with telemetry and other obvious malware purged - codium
# https://github.com/VSCodium/vscodium
# package at https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo
