# CURRENT SELECTION:
# codium (like vscode, but without proprietrary parts)

# https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo

---
# for quick editing
# geany geany-plugin-addons
- name: "Install Geany, as stopgap until Codium can be manually installed"
  apt:
    name: codium
    force_apt_get: yes
# TODO! for now do this manually
#- name: Add an Apt signing key, uses whichever key is at the URL
#  apt_key:
#    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
#    state: present
#- name: "Add repo"
#  apt_repository:
#    repo: 'deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main'
- name: "Install Codium"
  apt:
    name: codium
    force_apt_get: yes

# https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo#how-to-install-for-debianubuntulinux-mint
# should have an install instructions

# See also https://github.com/VSCodium/vscodium/issues/2032#issuecomment-2589260055

# note https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/issues/36#note_395793123

# version with telemetry and other obvious malware purged - codium
# https://github.com/VSCodium/vscodium
# package at https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo




# CRITERIA:
# decent text editor that works well out of the box
# - without endless configurations
# - sane defaults
# - but allow configuration
# - must have syntax code higligting
#  - ability to show whitespace (tabs vs spaces) is mandatory
# - preferably showing automated docs info for libraries (in Python, Ruby etc)
# - preferably smart tabs - use tabs/spaces depending on how file is formatted
# - no telemetry
#  - at this point believing that only private and limited data will be used
#    would be silly. This is sad as reasonable telemetry would help everyone.

# REJECTED EDITORS:
# sublime text requires manual configuration to work well
# - https://www.sublimetext.com/docs/3/linux_repositories.html
# gedit is worse than sublime text
# featherpad is unfriendly as a code editor
# - option to distinguish spaces and tabs is deeply buried
#   - Option -> Preferences -> Text -> Show whitespaces
# - and it is using tabs when editing Python files with spaces for intends
# - not showing line numbers by default
# - losing state on OS/program crash
# kate
# - fails on extremely long lines
#   - https://stackoverflow.com/a/70590302/4130619 (but that was Kate 19.12.3 from 2019, in 2022 it was what Ubuntu package included)
# - not showing line numbers by default ( https://superuser.com/q/918189/376651 )
# visual studio code
# - includes nonfree parts

# SELECTED
# Codium (visual studio code without unfree parts)
