---
- name: remove startup bloat - get rid of not needed apt-daily.service slowing down startup
 # systemd-analyze blame
 # systemd-analyze critical-chain
 # https://askubuntu.com/a/763070/349903 mentions a visualisation tool
 # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html has ansible specific documentation
 # This service was sitting on critical chain, delaying startup by multiple seconds
 # Just to be able to show annoying popups I disabled anyway
 # also, it can be put into cron if I really need it
  ansible.builtin.systemd:
    # sudo systemctl disable apt-daily.service --now
    name: apt-daily.service
    enabled: no
- name: remove startup bloat - get rid of not needed NetworkManager-wait-online.service slowing down startup
 # yes, really. It was delaying startup by 6 seconds (doubling it!) by waiting for connection.
 # why?
 # see logs in https://gist.github.com/matkoniecz/27031a4918944cb556e1742930e6d927
  ansible.builtin.systemd:
    # sudo systemctl disable NetworkManager-wait-online.service
    name: NetworkManager-wait-online.service
    enabled: no
# according to Lubuntu chat a misconfiguration in default systemd settings is Ubuntu bug
# I asked about following:
# Lubuntu, by default, waits with boot until network connection succeeds or fails which is quite pointless and noticeably increases boot time.
# See https://gist.github.com/matkoniecz/27031a4918944cb556e1742930e6d927 (12s->6s for time measured by systemd-analyze critical-chain)
#
# response:
#
# (irc) <guiverc> @matkoniecz, systemd is Ubuntu maintained (part of base system), not Lubuntu specific.
# (irc) <Maik> in that case he has to report it at ubuntu's end on Launchpad
#
# though given ads in apt-get I probably should not waste my time on that...
# https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1992026

# see https://askubuntu.com/questions/1451560/ubuntu-20-04-how-can-i-stop-waiting-for-networkmanager-service-during-startup
# for attempt to fix next issue

- name: remove startup bloat - get rid of indexer that was a CPU hog directly on startup
# I am not using its results, as far as I know
# even if I would be, then why it takes ENTIRE processor directly after startup?
# manages to make browser startup torturously slow
# found culprit using top command
# https://unix.stackexchange.com/questions/704220/what-is-tracker-miner-f-and-how-to-stop-it
# https://askubuntu.com/questions/876304/how-to-uninstall-all-trackers-tracker-miner-fs-apps
  apt:
    name: "{{ packages }}"
    state: absent
    force_apt_get: yes
  vars:
    packages:
      - tracker-extract

- name: remove raspbian bloat
  apt:
    name: "{{ packages }}"
    state: absent
    force_apt_get: yes
  vars:
    packages:
      - wolfram-engine
      - scratch
      - minecraft-pi
      - python-minecraftpi 
      - python3-minecraftpi
      - sonic-pi
      - dillo # web browser, supports only plain HTML/XHTML (with CSS rendering) and images over HTTP; scripting is ignored entirely
      - penguinspuzzle
# removals of default program may be undone by sudo apt-get -qq install lubuntu-desktop
- name: remove lubuntu 14 bloat
  apt:
    name:
      - leafpad # unwanted text editors
      - gedit # unwanted text editors
      - xpad
      - gnome-mplayer # though for me it seems that just ratings are missing - and maybe playlist persistence
      - abiword
      - gnumeric
      - audacious
      - transmission # bit-torrent client
      - transmission-gtk # bit-torrent client
      - transmission-cli # bit-torrent client
      - transmission-common # bit-torrent client
    state: absent
    force_apt_get: yes
- name: remove lubuntu 16 bloat
  apt:
    name:
      - pidgin
      - pidgin-data
      - sylpheed
    state: absent
    force_apt_get: yes
- name: remove lubuntu 18 bloat
  apt:
    name:
      - kdeconnect
      - kmail
    state: absent
    force_apt_get: yes
- name: remove lubuntu 19 bloat
  apt:
    name:
      - kdeconnect
      - muon
      - knotes
      - vim
      - qtpass
      - 2048-qt
      - trojita # maybe better than claws-mail? looks very similar
      - korganizer
      - featherpad # is not saving state in case of OS/program crash
      - lximage-qt # Why after deleting it keeps displaying deleted image?
                   # Instead of moving to the next one?
                   # It is confusing because it seems that message was not deleted,
                   # It slows down user. In what kind of situation user wants to delete
                   # image and keep looking at it?
                   # On top of that image is deleted permanently instead of being moved to a
                   # recycle bin.
                   # (feedback send to place recommended in "about" panel)
      - plasma-discover # for me it is an useless duplicate of apt-get
      - noblenote
    state: absent
    force_apt_get: yes
- name: remove lubuntu 20 bloat
  apt:
    name:
      - quassel # IRC client, I am not using IRC
      - fcitx # some special input method handling, for Chinese characters (???)
    state: absent
    force_apt_get: yes
- name: remove lubuntu bloat from unknown version
  apt:
    name:
      - aptitude # minesweeper bait in the main menu
      - light-locker # disable screen locking
      - ghostscript # launched by gs (conflicts with misspelled alias for git status)
      - gpicview # deletes without using trash
    state: absent
    force_apt_get: yes
- name: purge zeitgeist for disturbing backup diffs and being creepy and having no known use
  apt:
    name:
      - zeitgeist
      - zeitgeist-core
      - zeitgeist-datahub
      - zeitgeist-sharp
    state: absent
    purge: yes
    force_apt_get: yes
