---
- name: remove raspbian bloat
  apt:
    name: "{{ packages }}"
    state: absent
    force_apt_get: yes
  vars:
    packages:
      - wolfram-engine
      - scratch
      - minecraft-pi
      - python-minecraftpi 
      - python3-minecraftpi
      - sonic-pi
      - dillo # web browser, supports only plain HTML/XHTML (with CSS rendering) and images over HTTP; scripting is ignored entirely
      - penguinspuzzle
# removals of default program may be undone by sudo apt-get -qq install lubuntu-desktop
- name: remove lubuntu 14 bloat
  apt:
    name:
      - leafpad # unwanted text editors
      - gedit # unwanted text editors
      - xpad
      - gnome-mplayer # though for me it seems that just ratings are missing - and maybe playlist persistence
      - abiword
      - gnumeric
      - audacious
      - transmission # bit-torrent client
      - transmission-gtk # bit-torrent client
      - transmission-cli # bit-torrent client
      - transmission-common # bit-torrent client
    state: absent
    force_apt_get: yes
- name: remove lubuntu 16 bloat
  apt:
    name:
      - pidgin
      - pidgin-data
      - sylpheed
    state: absent
    force_apt_get: yes
- name: remove lubuntu 18 bloat
  apt:
    name:
      - kdeconnect
      - kmail
    state: absent
    force_apt_get: yes
- name: remove lubuntu 19 bloat
  apt:
    name:
      - kdeconnect
      - muon
      - knotes
      - vim
      - qtpass
      - 2048-qt
      - trojita # maybe better than claws-mail? looks very similar
      - korganizer
      - featherpad # is not saving state in case of OS/program crash
      - lximage-qt # Why after deleting it keeps displaying deleted image?
                   # Instead of moving to the next one?
                   # It is confusing because it seems that message was not deleted,
                   # It slows down user. In what kind of situation user wants to delete
                   # image and keep looking at it?
                   # On top of that image is deleted permanently instead of being moved to a
                   # recycle bin.
                   # (feedback send to place recommended in "about" panel)
      - plasma-discover # for me it is an useless duplicate of apt-get
      - noblenote
    state: absent
    force_apt_get: yes
- name: remove lubuntu 20 bloat
  apt:
    name:
      - quassel # IRC client, I am not using IRC
      - fcitx # some special input method handling, for Chinese characters (???)
    state: absent
    force_apt_get: yes
- name: remove lubuntu bloat from unknown version
  apt:
    name:
      - aptitude # minesweeper bait in the main menu
      - light-locker # disable screen locking
      - ghostscript # launched by gs (conflicts with mispelled alias for git status)
      - gpicview # deletes without using trash
    state: absent
    force_apt_get: yes
- name: purge zeitgeist for disturbing backup diffs and being creepy and having no known use
  apt:
    name:
      - zeitgeist
      - zeitgeist-core
      - zeitgeist-datahub
      - zeitgeist-sharp
    state: absent
    purge: yes
    force_apt_get: yes
