# https://docs.ansible.com/ansible/latest/modules/pip_module.html
---
- name: Install yt-dlp
  become: yes
  become_user: "{{ username_of_a_local_user }}"
  pip:
    name: yt-dlp
    extra_args: --user
    state: latest
